### ISSUE TITLE
Windows Release is missing the scripts folder

### ISSUE THREAD

**Issue by jacopomazzoni** [cnr-isti-vclab/relight#31]
I tried downloading the scripts folder from the master branch but when i select it in the preferences the software says it's looking for python versions of the sh files and those are missing.

**Comment by jacopomazzoni** [comment]
if launched manually deepzoom.py reports pyvips cannot be found, even after issuing pip3 install pyvips I think this might be the current point of failure.

C:\Users\jmazz\Desktop\obverse\rtiwin4\rti.png>python3 C:\Users\jmazz\Desktop\Relight1.0-windows\scripts\deepzoom.py ./
Traceback (most recent call last):
  File "C:\Users\jmazz\Desktop\Relight1.0-windows\scripts\deepzoom.py", line 2, in <module>
    from pyvips import Image
ModuleNotFoundError: No module named 'pyvips'

```
C:\Users\jmazz\Desktop\obverse\rtiwin4\rti.png>pip3 install pyvips
Requirement already satisfied: pyvips in c:\users\jmazz\appdata\local\programs\python\python39\lib\site-packages (2.1.15)
Requirement already satisfied: cffi>=1.0.0 in c:\users\jmazz\appdata\local\programs\python\python39\lib\site-packages (from pyvips) (1.14.6)
Requirement already satisfied: pycparser in c:\users\jmazz\appdata\local\programs\python\python39\lib\site-packages (from cffi>=1.0.0->pyvips) (2.20)

C:\Users\jmazz\Desktop\obverse\rtiwin4\rti.png>python3 C:\Users\jmazz\Desktop\Relight1.0-windows\scripts\deepzoom.py ./
Traceback (most recent call last):
  File "C:\Users\jmazz\Desktop\Relight1.0-windows\scripts\deepzoom.py", line 2, in <module>
    from pyvips import Image
ModuleNotFoundError: No module named 'pyvips'

C:\Users\jmazz\Desktop\obverse\rtiwin4\rti.png>
```
